<?php

/**
 * My Application bootstrap file.
 */
use Nette\Application\Routers\Route;


// Load Nette Framework or autoloader generated by Composer
require LIBS_DIR . '/lessc.inc.php';
require LIBS_DIR . '/autoload.php';


// Configure application
$configurator = new Nette\Config\Configurator;

// Enable Nette Debugger for error visualisation & logging
$configurator->setDebugMode(Nette\Config\Configurator::DEVELOPMENT);
//$configurator->setDebugMode($configurator::NONE);
$configurator->enableDebugger(__DIR__ . '/../log');
//\Nette\Diagnostics\Debugger::enable(\Nette\Diagnostics\Debugger::DEVELOPMENT);

// Enable RobotLoader - this will load all classes automatically
$configurator->setTempDirectory(__DIR__ . '/../temp');
$configurator->createRobotLoader()
	->addDirectory(APP_DIR)
	->addDirectory(LIBS_DIR)
	//->setCacheStorage(new Nette\Caching\Storages\MemoryStorage())
	->register();

$configurator->onCompile[] = function ($configurator, $compiler) {
    $compiler->addExtension('ajax', new VojtechDobes\NetteAjax\Extension);
};


$webloaderExtension = new \WebLoader\Nette\Extension();
$webloaderExtension->install($configurator);

// Create Dependency Injection container from config.neon file
$configurator->addConfig(__DIR__ . '/config/config.neon');
$container = $configurator->createContainer();

//Vodacek\Forms\Controls\DateInput::register();
Nette\Forms\Container::extensionMethod('addDatePicker', function (Nette\Forms\Container $container, $name, $label = NULL) {
    return $container[$name] = new JanTvrdik\Components\DatePicker($label);
});

// get list of existing pages from configuration
$existingPages = implode('|',array_keys($container->parameters['pageLayout']));

// Setup router
$container->router[] = new Route('index.php', 'Homepage:default', Route::ONE_WAY);
$container->router[] = new Route('', 'Homepage:default');
$container->router[] = new Route('style[/<item>]', 'Style:default');
if($existingPages != ""){
    // this one route is for backward compatibility with old edit link format from emails
    $container->router[] = new Route('<item '.$existingPages.'>/edit.php', 'Edit:default', Route::ONE_WAY);
    $container->router[] = new Route('<item '.$existingPages.'>/novy_zaznam/', 'Item:new');
    $container->router[] = new Route('<item '.$existingPages.'>/[<vc-filter>/][strana/<vp-page>/][razeni/<vc-orderBy>/[<vc-order>/]]', 'Item:default');
}
$container->router[] = new Route('kalendar/<page>/[<vc-filter>/][mesic/<calendar-year>/<calendar-month>/[<do>/]]',array(
														    'presenter'=>'Calendar',
														    'action'=>'default',
														    'do'=>array(
															Route::VALUE => NULL,
															Route::FILTER_TABLE => array(
															    'zmen'=>'calendar-changeMonth'
															)
														    )
														));
$container->router[] = new Route('<presenter>/<action>[/<hash>]', 'Homepage:default');


// Configure and run the application!
$container->application->run();
